SELECT survey.zipcode,
survey.city,
survey.state,
survey.agency,
survey.swnftemp,
survey.ftgangoff,
survey.ftdrugoff,
survey.ftterroff,
survey.numcpo,
survey.drivhis,
survey.cultdiv,
survey.white,
survey.black,
survey.hispanic,
survey.asian,
survey.nathaw,
survey.amerind,
survey.multrace,
survey.unkrace,
survey.male,
survey.female,
survey.carpat,
survey.footpat,
survey.cptrnnew,
survey.cptrninserv,
survey.cpmission,
survey.cpplan,
survey.cpnone,
survey.lessthanplcy,
survey.racialprplcy,
survey.numuofoth,
ratio.year,ratio.searches_over_stops_black_over_white AS "rpsi"
FROM searches_over_stops ratio 
JOIN nc_police_survey survey ON survey.agency_id = ratio.agency_id;