(lp0
S'totacad'
p1
aS'sgtmin'
p2
aS'diversity_index'
p3
aS'entrymin'
p4
aS'white_officer_disparity'
p5
aS'opbudget_per_capita'
p6
aS'sgtmax'
p7
aS'entrymax'
p8
aS'black_over_white_institutionalized_adult_disparity'
p9
aS'institutionalized_juvenile_white'
p10
aS'chiefmin'
p11
aS'numcarcam'
p12
aS'numfixcam_per_capita'
p13
aS'total_income_estimate_all_per_capita'
p14
aS'rural'
p15
aS'white_per_totofficers'
p16
aS'institutionalized_juvenile_all'
p17
aS'chiefmax'
p18
aS'numrespoff_per_capita'
p19
aS'black_over_white_institutionalized_disparity'
p20
aS'numcarcam_per_capita'
p21
aS'black_over_white_institutionalized_adult_local_jail_disparity'
p22
aS'numfixcam'
p23
aS'numsro_per_capita'
p24
aS'institutionalized_juvenile_white_per_capita'
p25
aS'institutionalized_juvenile_all_per_capita'
p26
aS'numothunm'
p27
aS'swnauthemp_per_capita'
p28
aS'civftemp'
p29
aS'civftemp_per_capita'
p30
aS'nummrkcars_per_capita'
p31
aS'swnauthemp'
p32
aS'hispanic_per_totofficers'
p33
aS'total_income_estimate_black_per_capita'
p34
aS'totinsrv'
p35
aS'drugforf_per_capita'
p36
aS'black_over_white_institutionalized_juvenile_disparity'
p37
aS'black_over_white_income_disparity'
p38
aS'unkrace'
p39
aS'numothunm_per_capita'
p40
aS'numumkcars_per_capita'
p41
aS'institutionalized_white_per_capita'
p42
aS'black_officer_disparity'
p43
a.